server:
  servlet:
    context-path: /lxzh
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/web?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowMutiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.lxzh.bean

#showSql
logging:
  level:
    com:
      lxzh:
        mapper : debug
imagepath: F:/image/
filepath: F:/file/
pageHelper:
  page: 1
  pageSize: 10